# Generated by Django 4.0 on 2022-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.IntegerField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
